version: 1.0.{build}
branches:
  only: 
  - master
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  description: Logging infrastructure for uShip
cache: packages -> **\packages.config
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore src\uShip.Logging.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: LAUvjakgzRSJgwdGkjrFEV/KRvUgWABPUuye+IcpCUwGRO+w/ZqxVV7okkGN1v1T
  skip_symbols: true
notifications:
- provider: Slack
  auth_token:
    secure: QYIi0MlTdmQItOynU70xq8OjW9q18zfNbcaI8bIXPBNBehcmn5s+bIpQWIGoCZDIUhO+ubDRFXMDNNZUztnGEQ==
  channel: appveyor
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
hosts:
  api.nuget.org: 93.184.221.200